[project]
name = "napari-organoid-segmentation"
version = "0.0.2"
description = "Simple napari tools for organoid mosaics, training of convpaint model, segmentation of organoids, and measurements."
author = [{name = "Sophie Mosegaard", email = "sophie.mosegaard@epfl.ch"}, {name = "Daniel Sage"}] readme = "README.md"
classifiers = [
    "Framework :: napari",
]
dependencies = [
    "napari",
    "numpy",
    "scikit-image",
    "magicgui",
    "pandas",
    "napari-convpaint",
    "roifile",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]

[project.entry-points."napari.manifest"]
napari-organoid-segmentation = "napari_organoid_segmentation:napari.yaml"